services:

#
#
# Config servers
#
#
  config-server-primary:
    image: mongo:7
    container_name: config-server-primary
    command: mongod --port 27017 --configsvr --replSet config-servers
    volumes:
      - ./init_scripts/init-repl-config-servers.js:/scripts/init-repl-config-servers.js:ro
    ports:
      - 27700:27017
    restart: always

  config-server-secondary:
    image: mongo:7
    container_name: config-server-secondary
    command: mongod --port 27017 --configsvr --replSet config-servers
    volumes:
      - ./init_scripts/init-repl-config-servers.js:/scripts/init-repl-config-servers.js:ro
    ports:
      - 27701:27017
    restart: always

#
#
# Mongos
#
#
  mongos-0:
    image: mongo:7
    container_name: mongos-0
    command: mongos --port 27017 --configdb config-servers/config-server-primary:27017,config-server-secondary:27017 --bind_ip_all
    ports:
      - 27600:27017
    restart: always
    volumes:
      - ./init_scripts/init-mongos.js:/scripts/init-mongos.js:ro
      - ./init_scripts/configure-sharding.js:/scripts/configure-sharding.js:ro
      - ./priklady.js:/scripts/priklady.js:ro
      - ./init_scripts/fixup-data.js:/scripts/fixup-data.js:ro
      - ./data/business.json:/data/business.json
      - ./data/review.json:/data/review.json
      - ./data/user.json:/data/user.json

  mongos-1:
    image: mongo:7
    container_name: mongos-1
    command: mongos --port 27017 --configdb config-servers/config-server-primary:27017,config-server-secondary:27017 --bind_ip_all
    ports:
      - 27601:27017
    restart: always
    volumes:
      - ./init_scripts/init-mongos.js:/scripts/init-mongos.js:ro
      - ./init_scripts/configure-sharding.js:/scripts/configure-sharding.js:ro

#
#
# Data servers
#
#

#
# Shard 0
#
  shard-0-primary:
    image: mongo:7
    container_name: shard-0-primary
    command: mongod --port 27017 --replSet shard-0 --shardsvr
    ports:
      - 27800:27017
    restart: always
    volumes:
      - ./init_scripts/init-repl-shard-0.js:/scripts/init-repl-shard-0.js:ro

  shard-0-secondary:
    image: mongo:7
    container_name: shard-0-secondary
    command: mongod --port 27017 --replSet shard-0 --shardsvr
    ports:
      - 27801:27017
    restart: always

#
# Shard 1
#
  shard-1-primary:
    image: mongo:7
    container_name: shard-1-primary
    command: mongod --port 27017 --replSet shard-1 --shardsvr
    ports:
      - 27900:27017
    restart: always
    volumes:
      - ./init_scripts/init-repl-shard-1.js:/scripts/init-repl-shard-1.js:ro

  shard-1-secondary:
    image: mongo:7
    container_name: shard-1-secondary
    command: mongod --port 27017 --replSet shard-1 --shardsvr
    ports:
      - 27901:27017
    restart: always
